spring.application.name=smarty

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:33306/sample-db
spring.datasource.username=root
spring.datasource.password=root

server.port=4000

logging.level.root=INFO